defaults: &defaults
  adapter: postgresql
  template: template0

development:
  <<: *defaults
  database: sofascab_development

test:
  <<: *defaults
  min_messages: warning #magic sauce
  database: sofascab_test